name: "Exerc√≠cio 2"

on: [push]

jobs:

  cria_e_upload_artefato:
    name: Cria artefato e faz upload
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: repositorio_do_juliano
          path: .
          retention-days: 15
